version: '3'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-angular
    container_name: frontend
    ports:
      - "80:80"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
